AllCops:
  TargetRubyVersion: 2.6.5

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Style/IfUnlessModifier:
  Enabled: false

Layout/LineLength:
  Max: 128

Metrics/MethodLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false